/**
 * DEMO SEED DATA — Zeva CBT guest mock trial content.
 * This content is ENTIRELY separate from an institution's real question bank.
 * It exists only so that a guest whose details don't match any student record
 * can still practice with a mock trial, WITHOUT ever seeing real/live exam
 * questions. Marked isDemo:true everywhere so it never appears in normal
 * admin question-bank listings or real exam selection.
 *
 * ~500 questions spread across 19 subjects (high school grades 7–12 in
 * English & Mathematics, college prep, and 5 professional bodies) so the
 * guest trial experience has real breadth rather than a handful of samples.
 */

function buildDemoContent() {
  const subjects = [];
  const questionsBySubjectKey = {};

  function addSubject(key, name, code, section, grade) {
    subjects.push({ key, name, code, section, grade, isDemo: true });
    questionsBySubjectKey[key] = [];
  }
  function q(key, text, options, correctIndex) {
    questionsBySubjectKey[key].push({ text, options, correctIndex, questionType: 'objective' });
  }


  // ---------------- HIGH SCHOOL ----------------
  // ---- Grade 7 ----
  addSubject("g7_eng", "English Language", "ENG", "high_school", "Grade 7");
  q("g7_eng", "Choose the correct plural of \"child\".", ["childs", "childes", "children", "childrens"], 2);
  q("g7_eng", "Which of these words is a noun?", ["Run", "Quickly", "Happiness", "Blue"], 2);
  q("g7_eng", "She ___ to school every day.", ["go", "goes", "going", "gone"], 1);
  q("g7_eng", "Choose the antonym of \"happy\".", ["Sad", "Glad", "Joyful", "Cheerful"], 0);
  q("g7_eng", "Which word is a proper noun?", ["city", "river", "Lagos", "mountain"], 2);
  q("g7_eng", "Choose the synonym of \"big\".", ["Small", "Large", "Tiny", "Short"], 1);
  q("g7_eng", "Identify the verb in: \"The dog barked loudly.\"", ["dog", "barked", "loudly", "the"], 1);
  q("g7_eng", "Neither Tom nor his friends ___ coming.", ["was", "were", "is", "am"], 1);
  q("g7_eng", "Choose the correct spelling.", ["Beleive", "Believe", "Belive", "Beleve"], 1);
  q("g7_eng", "What is the plural of \"mouse\"?", ["Mouses", "Mice", "Mices", "Mouse"], 1);
  q("g7_eng", "Identify the adjective in: \"She wore a beautiful dress.\"", ["wore", "beautiful", "dress", "she"], 1);
  q("g7_eng", "Choose the correct article: \"___ apple a day keeps the doctor away.\"", ["A", "An", "The", "No article"], 1);
  q("g7_eng", "What punctuation mark ends a question?", ["Full stop", "Comma", "Question mark", "Exclamation mark"], 2);
  q("g7_eng", "Which sentence is written correctly?", ["He dont like milk.", "He don’t likes milk.", "He doesn’t like milk.", "He not like milk."], 2);
  q("g7_eng", "Identify the pronoun in: \"They went to the market.\"", ["went", "the", "They", "market"], 2);
  q("g7_eng", "Choose the correct past tense of \"eat\".", ["Eated", "Ate", "Eaten", "Eating"], 1);
  q("g7_eng", "What is the opposite of \"difficult\"?", ["Hard", "Easy", "Complex", "Tough"], 1);
  q("g7_eng", "Which word means the same as \"quick\"?", ["Slow", "Fast", "Lazy", "Calm"], 1);
  q("g7_eng", "Choose the correct sentence.", ["I is happy.", "I am happy.", "I are happy.", "I be happy."], 1);
  q("g7_eng", "Identify the conjunction: \"I like tea but not coffee.\"", ["like", "but", "not", "tea"], 1);
  q("g7_eng", "What is a word that describes an action called?", ["Noun", "Verb", "Adjective", "Preposition"], 1);
  q("g7_eng", "Choose the correctly punctuated sentence.", ["Wow, that is amazing!", "Wow that is amazing", "wow, that is amazing!", "Wow that is amazing."], 0);
  q("g7_eng", "What is the singular form of \"leaves\"?", ["Leafs", "Leave", "Leaf", "Leaves"], 2);
  q("g7_eng", "Which of the following is a preposition?", ["Under", "Run", "Happy", "Slowly"], 0);
  q("g7_eng", "Choose the correct sentence in the future tense.", ["I will go tomorrow.", "I went tomorrow.", "I go tomorrow yesterday.", "I am gone tomorrow."], 0);
  q("g7_eng", "What do we call a group of words that expresses a complete thought?", ["Phrase", "Sentence", "Paragraph", "Clause"], 1);
  q("g7_eng", "Identify the correctly capitalised sentence.", ["my name is John.", "My Name Is John.", "My name is John.", "MY NAME IS JOHN."], 2);

  addSubject("g7_math", "Mathematics", "MTH", "high_school", "Grade 7");
  q("g7_math", "What is 15 + 27?", ["40", "41", "42", "43"], 2);
  q("g7_math", "Simplify: 3 + 4 x 2", ["14", "11", "10", "20"], 1);
  q("g7_math", "What is half of 84?", ["40", "42", "44", "46"], 1);
  q("g7_math", "Convert 0.5 to a fraction.", ["1/4", "1/2", "1/3", "2/5"], 1);
  q("g7_math", "What is the perimeter of a square with side 6cm?", ["12cm", "18cm", "24cm", "36cm"], 2);
  q("g7_math", "What is 9 squared?", ["18", "72", "81", "90"], 2);
  q("g7_math", "Which number is a prime number?", ["9", "15", "17", "21"], 2);
  q("g7_math", "What is 100 divided by 4?", ["20", "25", "30", "40"], 1);
  q("g7_math", "What is 6 x 7?", ["36", "40", "42", "48"], 2);
  q("g7_math", "Round 47 to the nearest 10.", ["40", "45", "50", "47"], 2);
  q("g7_math", "What is 3/4 as a decimal?", ["0.34", "0.75", "0.43", "0.25"], 1);
  q("g7_math", "What is the sum of the angles in a triangle?", ["90°", "180°", "270°", "360°"], 1);
  q("g7_math", "What is 12 - 5 + 3?", ["4", "10", "20", "14"], 1);
  q("g7_math", "What is the value of 5²?", ["10", "15", "25", "20"], 2);
  q("g7_math", "Which of these is an even number?", ["13", "21", "18", "35"], 2);
  q("g7_math", "What is the area of a rectangle 4cm by 5cm?", ["9cm²", "18cm²", "20cm²", "22cm²"], 2);
  q("g7_math", "What is 1/2 + 1/4?", ["1/6", "2/6", "3/4", "2/4"], 2);
  q("g7_math", "What is the smallest whole number?", ["-1", "0", "1", "10"], 1);
  q("g7_math", "Convert 40% to a fraction.", ["2/5", "4/5", "1/4", "1/5"], 0);
  q("g7_math", "What is 8 x 9?", ["62", "72", "82", "81"], 1);
  q("g7_math", "What is the HCF of 12 and 18?", ["2", "3", "6", "9"], 2);
  q("g7_math", "What comes next: 5, 10, 15, 20, ___?", ["22", "24", "25", "30"], 2);
  q("g7_math", "What is 100 - 37?", ["63", "67", "73", "53"], 0);
  q("g7_math", "A triangle with all sides equal is called?", ["Scalene", "Isosceles", "Equilateral", "Right-angled"], 2);
  q("g7_math", "What is 3 x (4 + 2)?", ["14", "18", "20", "12"], 1);
  q("g7_math", "What is 15% of 200?", ["15", "20", "30", "45"], 2);
  q("g7_math", "How many sides does a hexagon have?", ["5", "6", "7", "8"], 1);

  // ---- Grade 8 ----
  addSubject("g8_eng", "English Language", "ENG", "high_school", "Grade 8");
  q("g8_eng", "Choose the correctly spelt word.", ["Recieve", "Receive", "Receeve", "Receve"], 1);
  q("g8_eng", "Identify the adjective: \"The tall boy ran fast.\"", ["boy", "tall", "ran", "fast"], 1);
  q("g8_eng", "What is the plural of \"goose\"?", ["Gooses", "Geese", "Goosies", "Geeses"], 1);
  q("g8_eng", "Choose the correct sentence.", ["He don’t like rice.", "He doesn’t like rice.", "He not like rice.", "He no like rice."], 1);
  q("g8_eng", "What type of word is \"quickly\"?", ["Noun", "Verb", "Adverb", "Pronoun"], 2);
  q("g8_eng", "Choose the correct past tense of \"go\".", ["Goed", "Gone", "Went", "Going"], 2);
  q("g8_eng", "Which is a compound word?", ["Sunset", "Happy", "Running", "Blue"], 0);
  q("g8_eng", "Identify the pronoun: \"She gave it to him.\"", ["gave", "she", "to", "him"], 1);
  q("g8_eng", "Choose the correct comparative form of \"good\".", ["Gooder", "Better", "Best", "More good"], 1);
  q("g8_eng", "What is the superlative form of \"tall\"?", ["Taller", "Tallest", "More tall", "Most tall"], 1);
  q("g8_eng", "Identify the direct object: \"Musa kicked the ball.\"", ["Musa", "kicked", "the ball", "the"], 2);
  q("g8_eng", "Choose the correctly punctuated sentence.", ["Where are you going", "Where are you going?", "where are you going?", "Where, are you going?"], 1);
  q("g8_eng", "What figure of speech compares two things using \"like\" or \"as\"?", ["Metaphor", "Simile", "Personification", "Hyperbole"], 1);
  q("g8_eng", "Which word is spelt correctly?", ["Definately", "Definitely", "Definitly", "Definetly"], 1);
  q("g8_eng", "Choose the correct tense: \"By next year, she ___ her studies.\"", ["will complete", "completed", "will have completed", "completes"], 2);
  q("g8_eng", "What is a word that joins two clauses called?", ["Preposition", "Conjunction", "Interjection", "Article"], 1);
  q("g8_eng", "Identify the collective noun: \"A herd of cattle grazed.\"", ["cattle", "herd", "grazed", "a"], 1);
  q("g8_eng", "Choose the antonym of \"generous\".", ["Kind", "Stingy", "Giving", "Warm"], 1);
  q("g8_eng", "What is the correct indirect speech of: He said, \"I am tired.\"", ["He said he am tired.", "He said that he was tired.", "He say he was tired.", "He said I am tired."], 1);
  q("g8_eng", "Which of these is an interjection?", ["Run", "Ouch!", "Slowly", "Table"], 1);
  q("g8_eng", "Which of these words is spelt correctly?", ["Occassion", "Ocasion", "Occasion", "Ocassion"], 2);
  q("g8_eng", "Identify the subject in: \"The teacher explained the topic.\"", ["The teacher", "explained", "the topic", "topic"], 0);
  q("g8_eng", "What does the prefix \"un-\" usually mean?", ["Again", "Not", "Before", "After"], 1);
  q("g8_eng", "Choose the correct plural of \"knife\".", ["Knifes", "Knives", "Knifves", "Knife"], 1);
  q("g8_eng", "Which sentence uses correct subject-verb agreement?", ["The team are winning.", "The team is winning.", "The team am winning.", "The team be winning."], 1);
  q("g8_eng", "What is the meaning of the idiom \"break the ice\"?", ["To damage something", "To start a conversation in a relaxed way", "To cause an argument", "To end a friendship"], 1);
  q("g8_eng", "Identify the correctly formed question tag: \"She is coming, ___?\"", ["isn't it", "isn't she", "doesn't she", "wasn't she"], 1);

  addSubject("g8_math", "Mathematics", "MTH", "high_school", "Grade 8");
  q("g8_math", "Solve for x: x + 5 = 12", ["5", "6", "7", "8"], 2);
  q("g8_math", "What is 25% of 200?", ["25", "50", "75", "100"], 1);
  q("g8_math", "Find the area of a rectangle 5cm by 8cm.", ["13cm²", "30cm²", "40cm²", "45cm²"], 2);
  q("g8_math", "What is the value of 2³?", ["6", "8", "9", "12"], 1);
  q("g8_math", "Simplify: 5(x + 2)", ["5x + 2", "5x + 10", "x + 10", "5x + 7"], 1);
  q("g8_math", "What is the LCM of 4 and 6?", ["8", "10", "12", "24"], 2);
  q("g8_math", "Convert 3/4 to a percentage.", ["34%", "43%", "75%", "80%"], 2);
  q("g8_math", "What is the next number: 3, 6, 12, 24, ___?", ["30", "36", "48", "42"], 2);
  q("g8_math", "Solve for y: 3y = 18", ["5", "6", "7", "9"], 1);
  q("g8_math", "What is the circumference formula for a circle of radius r?", ["πr²", "2πr", "πr", "r²"], 1);
  q("g8_math", "What is -8 + 5?", ["-13", "-3", "3", "13"], 1);
  q("g8_math", "Simplify: 4x + 3x - x", ["6x", "7x", "8x", "5x"], 1);
  q("g8_math", "What is the median of: 3, 7, 9, 12, 15?", ["7", "9", "12", "10"], 1);
  q("g8_math", "What is 60% written as a decimal?", ["0.06", "0.6", "6.0", "0.006"], 1);
  q("g8_math", "A rectangle has length 10cm and width 4cm. What is its perimeter?", ["14cm", "24cm", "28cm", "40cm"], 2);
  q("g8_math", "What is the value of x in 2x - 4 = 10?", ["5", "6", "7", "8"], 2);
  q("g8_math", "What is the probability of getting heads when tossing a fair coin?", ["1/4", "1/3", "1/2", "1"], 2);
  q("g8_math", "What is 7 squared minus 3 squared?", ["30", "34", "40", "46"], 2);
  q("g8_math", "Simplify: (2x)(3x)", ["5x", "6x", "5x²", "6x²"], 3);
  q("g8_math", "What type of angle is 95°?", ["Acute", "Right", "Obtuse", "Reflex"], 2);
  q("g8_math", "What is the GCF of 18 and 24?", ["2", "3", "6", "9"], 2);
  q("g8_math", "A number decreased by 7 is 20. What is the number?", ["13", "20", "27", "17"], 2);
  q("g8_math", "What is 3/5 of 40?", ["20", "24", "28", "32"], 1);
  q("g8_math", "Which of these is an equation?", ["3x + 2", "3x + 2 = 8", "3x > 2", "3x"], 1);
  q("g8_math", "What is the sum of interior angles of a quadrilateral?", ["180°", "270°", "360°", "450°"], 2);
  q("g8_math", "What is 0.75 as a fraction in lowest terms?", ["3/4", "7/10", "75/10", "3/5"], 0);
  q("g8_math", "Solve: 4(x - 1) = 12", ["3", "4", "5", "6"], 1);

  // ---- Grade 9 ----
  addSubject("g9_eng", "English Language", "ENG", "high_school", "Grade 9");
  q("g9_eng", "Choose the option that best completes: \"Neither the teacher nor the students ___ ready.\"", ["was", "were", "is", "has been"], 1);
  q("g9_eng", "Select the correctly spelt word.", ["Accomodate", "Acommodate", "Accommodate", "Acomodate"], 2);
  q("g9_eng", "Identify the figure of speech: \"The wind whispered through the trees.\"", ["Simile", "Metaphor", "Personification", "Hyperbole"], 2);
  q("g9_eng", "Choose the correct passive form of: \"The teacher taught the class.\"", ["The class taught the teacher.", "The class was taught by the teacher.", "The class is teaching.", "The teacher was taught."], 1);
  q("g9_eng", "What is a synonym for \"abundant\"?", ["Scarce", "Plentiful", "Limited", "Rare"], 1);
  q("g9_eng", "Identify the preposition: \"The book is on the table.\"", ["book", "is", "on", "table"], 2);
  q("g9_eng", "Choose the correct question tag: \"You are coming, ___?\"", ["isn't it", "aren't you", "don't you", "won't you"], 1);
  q("g9_eng", "What does the idiom \"bite the bullet\" mean?", ["To eat quickly", "To face something difficult bravely", "To argue", "To relax"], 1);
  q("g9_eng", "Choose the correctly punctuated sentence.", ["Its a lovely day.", "It's a lovely day.", "Its' a lovely day.", "It is a lovely day"], 1);
  q("g9_eng", "What is the meaning of \"meticulous\"?", ["Careless", "Very careful and precise", "Lazy", "Quick"], 1);
  q("g9_eng", "Identify the type of sentence: \"What a beautiful sunset!\"", ["Declarative", "Interrogative", "Imperative", "Exclamatory"], 3);
  q("g9_eng", "Choose the correct relative pronoun: \"The man ___ called yesterday is my uncle.\"", ["which", "who", "whom", "whose"], 1);
  q("g9_eng", "What is an example of alliteration?", ["The sun is a golden ball.", "Peter Piper picked a peck of pickled peppers.", "The wind howled.", "She sells seashells (once)."], 1);
  q("g9_eng", "Choose the correctly spelt word.", ["Embarass", "Embarrass", "Embaras", "Embarras"], 1);
  q("g9_eng", "What is the plural of \"criterion\"?", ["Criterions", "Criteria", "Criterias", "Criterion"], 1);
  q("g9_eng", "Identify the clause type: \"Although it was raining, we went out.\"", ["Independent clause", "Dependent clause", "Noun clause", "Relative clause"], 1);
  q("g9_eng", "Choose the correct word: \"The effect of the policy was ___.\"", ["affective", "effective", "affected", "effected"], 1);
  q("g9_eng", "What is a metaphor?", ["A comparison using \"like\" or \"as\"", "A direct comparison without using \"like\" or \"as\"", "An exaggeration", "A sound-imitating word"], 1);
  q("g9_eng", "Choose the antonym of \"diligent\".", ["Hardworking", "Lazy", "Careful", "Attentive"], 1);
  q("g9_eng", "Identify the correct spelling.", ["Rythm", "Rhythem", "Rhythm", "Rhithm"], 2);
  q("g9_eng", "What is onomatopoeia?", ["A word that imitates a sound", "A word with opposite meaning", "A repeated consonant sound", "A type of rhyme"], 0);
  q("g9_eng", "Choose the correct conditional: \"If it rains, we ___ stay indoors.\"", ["will", "would", "would have", "had"], 0);
  q("g9_eng", "What is the correct plural of \"analysis\"?", ["Analysises", "Analyses", "Analysis", "Analysi"], 1);
  q("g9_eng", "Identify the appropriate word: \"The committee ___ its decision yesterday.\"", ["announce", "announced", "announces", "announcing"], 1);
  q("g9_eng", "What literary device repeats the same word at the start of successive clauses?", ["Anaphora", "Simile", "Irony", "Assonance"], 0);
  q("g9_eng", "Choose the correct form: \"She is one of the students who ___ always punctual.\"", ["is", "are", "was", "has been"], 1);
  q("g9_eng", "What does \"verbose\" mean?", ["Using too many words", "Speaking briefly", "Silent", "Polite"], 0);

  addSubject("g9_math", "Mathematics", "MTH", "high_school", "Grade 9");
  q("g9_math", "Simplify: 3x + 5x - 2x", ["6x", "8x", "10x", "4x"], 0);
  q("g9_math", "What is the value of x if 2x + 6 = 20?", ["5", "6", "7", "8"], 1);
  q("g9_math", "Find the next number: 2, 4, 8, 16, ___", ["18", "24", "32", "20"], 2);
  q("g9_math", "What is the square root of 144?", ["11", "12", "13", "14"], 1);
  q("g9_math", "Solve for x: 5x - 3 = 17", ["3", "4", "5", "6"], 2);
  q("g9_math", "What is the volume of a cube with side 4cm?", ["16cm³", "48cm³", "64cm³", "32cm³"], 2);
  q("g9_math", "Factorise: x² - 9", ["(x-3)(x-3)", "(x+3)(x-3)", "(x+9)(x-1)", "(x-9)(x+1)"], 1);
  q("g9_math", "What is the gradient of a line joining (0,0) and (4,8)?", ["1", "2", "4", "8"], 1);
  q("g9_math", "What is 2⁴?", ["8", "12", "16", "32"], 2);
  q("g9_math", "Solve the inequality: x + 3 > 7", ["x > 4", "x < 4", "x > 10", "x < 10"], 0);
  q("g9_math", "What is the sum of the interior angles of a pentagon?", ["360°", "450°", "540°", "600°"], 2);
  q("g9_math", "Simplify: (x + 2)(x + 3)", ["x² + 5x + 6", "x² + 6x + 5", "x² + 5x + 5", "x² + 6"], 0);
  q("g9_math", "What is the mean of: 4, 8, 6, 10, 12?", ["7", "8", "9", "10"], 1);
  q("g9_math", "What is the value of √81?", ["8", "9", "10", "11"], 1);
  q("g9_math", "Convert 0.125 to a fraction.", ["1/8", "1/4", "1/6", "1/10"], 0);
  q("g9_math", "A car travels 240km in 4 hours. What is its average speed?", ["50km/h", "55km/h", "60km/h", "65km/h"], 2);
  q("g9_math", "What is the reciprocal of 3/5?", ["3/5", "5/3", "-3/5", "1/5"], 1);
  q("g9_math", "Solve for x: x/3 = 9", ["3", "12", "27", "36"], 2);
  q("g9_math", "What is the surface area of a cube with side 3cm?", ["9cm²", "27cm²", "54cm²", "18cm²"], 2);
  q("g9_math", "What is 15% of 80?", ["8", "10", "12", "15"], 2);
  q("g9_math", "If y = 2x + 1 and x = 3, what is y?", ["5", "6", "7", "8"], 2);
  q("g9_math", "What is the mode of: 2, 3, 3, 5, 7, 3, 8?", ["2", "3", "5", "7"], 1);
  q("g9_math", "Simplify: 2(3x - 4) + 5", ["6x - 3", "6x + 1", "6x - 9", "6x + 5"], 0);
  q("g9_math", "What is the value of x if x² = 49?", ["±7", "7 only", "-7 only", "49"], 0);
  q("g9_math", "What is the perimeter of a circle called?", ["Area", "Diameter", "Circumference", "Radius"], 2);
  q("g9_math", "Simplify the ratio 12:18 to lowest terms.", ["2:3", "3:4", "4:6", "6:9"], 0);
  q("g9_math", "What is the range of the data set: 5, 9, 12, 3, 18?", ["13", "15", "18", "9"], 1);

  // ---- Grade 10 ----
  addSubject("g10_eng", "English Language", "ENG", "high_school", "Grade 10");
  q("g10_eng", "Choose the correct meaning of \"ambiguous\".", ["Clear", "Having more than one possible meaning", "Certain", "Simple"], 1);
  q("g10_eng", "Identify the type of clause: \"That he lied was obvious.\"", ["Adjective clause", "Adverb clause", "Noun clause", "Independent clause"], 2);
  q("g10_eng", "Choose the correct sentence.", ["Each of the students have a book.", "Each of the students has a book.", "Each of the students having a book.", "Each of student has a book."], 1);
  q("g10_eng", "What is a euphemism?", ["A harsh expression", "A mild expression replacing a harsh one", "A type of rhyme", "A grammatical error"], 1);
  q("g10_eng", "Choose the correctly spelt word.", ["Concious", "Consious", "Conscious", "Consciouss"], 2);
  q("g10_eng", "What does \"procrastinate\" mean?", ["To act quickly", "To delay or postpone action", "To finish early", "To organise"], 1);
  q("g10_eng", "Identify the figure of speech: \"He is as brave as a lion.\"", ["Metaphor", "Simile", "Personification", "Irony"], 1);
  q("g10_eng", "Choose the correct form: \"She has been ___ since morning.\"", ["work", "working", "worked", "works"], 1);
  q("g10_eng", "What is the meaning of \"candid\"?", ["Dishonest", "Frank and open", "Secretive", "Aggressive"], 1);
  q("g10_eng", "Identify the correctly punctuated sentence.", ["My favourite fruits are: mango, orange and apple.", "My favourite fruits are; mango, orange and apple.", "My favourite fruits are mango, orange, and apple.", "My favourite fruits are, mango, orange and apple."], 2);
  q("g10_eng", "What is dramatic irony?", ["When a character says something ironic", "When the audience knows something a character doesn’t", "A funny situation", "A tragic ending"], 1);
  q("g10_eng", "Choose the correct word: \"The number of students ___ increasing.\"", ["is", "are", "were", "have"], 0);
  q("g10_eng", "What is the antonym of \"benevolent\"?", ["Kind", "Malevolent", "Generous", "Charitable"], 1);
  q("g10_eng", "Identify the type of sentence: \"Close the door.\"", ["Declarative", "Interrogative", "Imperative", "Exclamatory"], 2);
  q("g10_eng", "What is a soliloquy?", ["A conversation between two characters", "A speech a character gives alone expressing thoughts", "A song in a play", "A stage direction"], 1);
  q("g10_eng", "Which of these words is spelt correctly?", ["Neccessary", "Necesary", "Necessary", "Neccesary"], 2);
  q("g10_eng", "What does \"eloquent\" describe?", ["Someone who speaks fluently and persuasively", "Someone who is silent", "Someone who is rude", "Someone who is confused"], 0);
  q("g10_eng", "Identify the correct indirect speech: She said, \"I will come tomorrow.\"", ["She said she will come tomorrow.", "She said she would come the next day.", "She said I will come tomorrow.", "She say she would come tomorrow."], 1);
  q("g10_eng", "What is a paradox?", ["A statement that contradicts itself but may reveal truth", "A simple comparison", "A rhyme scheme", "A grammatical rule"], 0);
  q("g10_eng", "Choose the correct preposition: \"She is afraid ___ spiders.\"", ["of", "from", "with", "about"], 0);
  q("g10_eng", "What is the meaning of \"resilient\"?", ["Easily broken", "Able to recover quickly from difficulties", "Weak", "Slow to change"], 1);
  q("g10_eng", "Identify the correctly formed passive sentence: \"They built the house in 1990.\"", ["The house built in 1990.", "The house was built in 1990.", "The house is built in 1990.", "The house has built in 1990."], 1);
  q("g10_eng", "What is assonance?", ["Repetition of consonant sounds", "Repetition of vowel sounds in nearby words", "A type of rhyme scheme", "A play on words"], 1);
  q("g10_eng", "Choose the correct word: \"Their performance was ___ than expected.\"", ["good", "better", "best", "well"], 1);
  q("g10_eng", "What is the meaning of \"ubiquitous\"?", ["Rare", "Present everywhere", "Hidden", "Ancient"], 1);
  q("g10_eng", "Identify the mood: \"If I were rich, I would travel the world.\"", ["Indicative", "Imperative", "Subjunctive", "Interrogative"], 2);
  q("g10_eng", "What is a protagonist?", ["The villain of a story", "The main character of a story", "A minor character", "The narrator only"], 1);

  addSubject("g10_math", "Mathematics", "MTH", "high_school", "Grade 10");
  q("g10_math", "Solve: 2x² = 32", ["x = ±4", "x = 4 only", "x = 16", "x = 8"], 0);
  q("g10_math", "What is the value of sin 90°?", ["0", "0.5", "1", "√2"], 2);
  q("g10_math", "Factorise: x² + 5x + 6", ["(x+2)(x+3)", "(x+1)(x+6)", "(x-2)(x-3)", "(x+6)(x-1)"], 0);
  q("g10_math", "What is the equation of a straight line with gradient 2 passing through (0,3)?", ["y = 2x + 3", "y = 3x + 2", "y = 2x - 3", "y = x + 3"], 0);
  q("g10_math", "What is the value of log₁₀ 100?", ["1", "2", "10", "100"], 1);
  q("g10_math", "Solve the quadratic: x² - 5x + 6 = 0", ["x = 2, 3", "x = 1, 6", "x = -2, -3", "x = 5, 6"], 0);
  q("g10_math", "What is the value of cos 0°?", ["0", "0.5", "1", "-1"], 2);
  q("g10_math", "Simplify: (2x³)(3x²)", ["5x⁵", "6x⁵", "6x⁶", "5x⁶"], 1);
  q("g10_math", "What is the sum of the first 5 terms of the sequence 2, 4, 6, 8, 10?", ["20", "25", "30", "35"], 2);
  q("g10_math", "What is the discriminant of x² + 2x + 1 = 0?", ["0", "4", "-4", "8"], 0);
  q("g10_math", "What is the volume of a cylinder with radius 3cm and height 7cm? (use π ≈ 22/7)", ["198cm³", "132cm³", "154cm³", "176cm³"], 0);
  q("g10_math", "Simplify: √50", ["5√2", "2√5", "10√5", "25√2"], 0);
  q("g10_math", "What is the probability of rolling a 6 on a fair die?", ["1/2", "1/3", "1/6", "1/4"], 2);
  q("g10_math", "What is 3! (3 factorial)?", ["3", "6", "9", "12"], 1);
  q("g10_math", "If f(x) = 2x + 1, what is f(3)?", ["5", "6", "7", "8"], 2);
  q("g10_math", "What is the midpoint of (2,4) and (6,8)?", ["(4,6)", "(3,5)", "(8,12)", "(4,4)"], 0);
  q("g10_math", "Simplify: x⁵ ÷ x²", ["x²", "x³", "x⁷", "x"], 1);
  q("g10_math", "What is the interior angle sum of an octagon?", ["720°", "900°", "1080°", "1440°"], 2);
  q("g10_math", "What is 5⁰?", ["0", "1", "5", "50"], 1);
  q("g10_math", "Solve: |x - 3| = 5", ["x = 8 or x = -2", "x = 8 only", "x = -2 only", "x = 2 or x = -8"], 0);
  q("g10_math", "What is the distance between points (0,0) and (3,4)?", ["4", "5", "6", "7"], 1);
  q("g10_math", "Simplify: (x + 3)²", ["x² + 9", "x² + 6x + 9", "x² + 3x + 9", "x² + 6x + 6"], 1);
  q("g10_math", "What is the value of tan 45°?", ["0", "0.5", "1", "√3"], 2);
  q("g10_math", "What is the nth term of the sequence 3, 6, 9, 12?", ["n + 3", "3n", "n²", "3n + 1"], 1);
  q("g10_math", "A bag has 4 red and 6 blue balls. What is the probability of picking a red ball?", ["2/5", "3/5", "2/3", "1/2"], 0);
  q("g10_math", "What is 2³ × 2²?", ["2⁵", "2⁶", "4⁵", "4⁶"], 0);
  q("g10_math", "Simplify: 6x² ÷ 2x", ["3x", "4x", "3x²", "12x"], 0);

  // ---- Grade 11 ----
  addSubject("g11_eng", "English Language", "ENG", "high_school", "Grade 11");
  q("g11_eng", "What is the meaning of \"pragmatic\"?", ["Idealistic", "Dealing with things sensibly and practically", "Emotional", "Theoretical"], 1);
  q("g11_eng", "Identify the literary device: \"Time is a thief.\"", ["Simile", "Metaphor", "Alliteration", "Onomatopoeia"], 1);
  q("g11_eng", "Choose the correct sentence.", ["Between you and I, this is wrong.", "Between you and me, this is wrong.", "Between I and you, this is wrong.", "Between you and myself, this is wrong."], 1);
  q("g11_eng", "What does \"ephemeral\" mean?", ["Lasting a very short time", "Permanent", "Ancient", "Powerful"], 0);
  q("g11_eng", "Identify the correctly formed subjunctive: \"I suggest that he ___ early.\"", ["leaves", "leave", "left", "leaving"], 1);
  q("g11_eng", "What is a syllogism?", ["A form of logical reasoning with two premises and a conclusion", "A type of poem", "A grammatical error", "A figure of speech"], 0);
  q("g11_eng", "Choose the correct word: \"The evidence was ___ to convict him.\"", ["insufficient", "unsufficient", "insuficient", "inssuficient"], 0);
  q("g11_eng", "What is the meaning of \"cogent\"?", ["Weak and unconvincing", "Clear, logical and convincing", "Confusing", "Emotional"], 1);
  q("g11_eng", "Identify the tone: \"Oh great, another Monday morning.\"", ["Sincere", "Sarcastic", "Joyful", "Neutral"], 1);
  q("g11_eng", "Choose the correctly spelt word.", ["Priviledge", "Privilege", "Privelege", "Privillege"], 1);
  q("g11_eng", "What is a caesura in poetry?", ["A pause or break within a line of verse", "A rhyme scheme", "The final line of a poem", "A stanza"], 0);
  q("g11_eng", "Choose the correct usage: \"He is different ___ his brother.\"", ["than", "to", "from", "with"], 2);
  q("g11_eng", "What does \"verisimilitude\" mean in literature?", ["The appearance of being true or real", "A grammatical structure", "A poetic rhythm", "A type of narrator"], 0);
  q("g11_eng", "Identify the correctly punctuated sentence.", ["The teacher's book is on the table.", "The teachers' book is on the table.", "The teachers book is on the table.", "The teacher's' book is on the table."], 0);
  q("g11_eng", "What is an antithesis?", ["A contrast of ideas expressed in balanced phrases", "A sound device", "A rhyme scheme", "A type of narrator"], 0);
  q("g11_eng", "Identify the grammatically correct sentence.", ["If I was you, I would apologise.", "If I were you, I would apologise.", "If I am you, I would apologise.", "If I be you, I would apologise."], 1);
  q("g11_eng", "What is the meaning of \"obsolete\"?", ["Modern", "No longer in use", "Rare but valuable", "Expensive"], 1);
  q("g11_eng", "Identify the narrative point of view: \"I walked into the room and saw him.\"", ["First person", "Second person", "Third person limited", "Third person omniscient"], 0);
  q("g11_eng", "What does \"juxtaposition\" mean?", ["Placing two things close together to highlight contrast", "A type of rhyme", "A repeated sound", "A grammatical tense"], 0);
  q("g11_eng", "Choose the correct word: \"She was ___ by the sad news.\"", ["effected", "affected", "effecting", "affective"], 1);
  q("g11_eng", "What is a rhetorical question?", ["A question asked for genuine information", "A question asked for effect, not requiring an answer", "A yes/no question", "A tag question"], 1);
  q("g11_eng", "Identify the correctly spelt word.", ["Occurence", "Occurrence", "Ocurrence", "Occurrance"], 1);
  q("g11_eng", "What does \"hyperbole\" mean?", ["Deliberate exaggeration for effect", "Understatement", "A direct comparison", "A sound-imitating word"], 0);
  q("g11_eng", "Choose the correct usage: \"The committee ___ divided on the issue.\"", ["is", "are", "was", "has"], 1);
  q("g11_eng", "What is the meaning of \"innate\"?", ["Learned through experience", "Present from birth", "Foreign", "Temporary"], 1);
  q("g11_eng", "Identify the type of irony: A fire station burns down.", ["Verbal irony", "Dramatic irony", "Situational irony", "Cosmic irony"], 2);
  q("g11_eng", "What is the correct meaning of \"empathy\"?", ["Feeling sorry for someone", "The ability to understand and share the feelings of another", "Indifference", "Jealousy"], 1);

  addSubject("g11_math", "Mathematics", "MTH", "high_school", "Grade 11");
  q("g11_math", "Differentiate y = x² with respect to x.", ["x", "2x", "x²", "2"], 1);
  q("g11_math", "What is the value of ∫2x dx?", ["x² + C", "2x² + C", "x + C", "2 + C"], 0);
  q("g11_math", "Solve the simultaneous equations: x + y = 7, x - y = 1", ["x=4, y=3", "x=3, y=4", "x=5, y=2", "x=2, y=5"], 0);
  q("g11_math", "What is the value of sin²θ + cos²θ?", ["0", "1", "2", "θ"], 1);
  q("g11_math", "What is the sum to infinity of a geometric series with a=4, r=1/2?", ["6", "7", "8", "9"], 2);
  q("g11_math", "Solve: log₂ 8 = ?", ["2", "3", "4", "8"], 1);
  q("g11_math", "What is the derivative of a constant?", ["1", "0", "The constant itself", "Undefined"], 1);
  q("g11_math", "What is the 5th term of an AP with first term 3 and common difference 4?", ["15", "17", "19", "23"], 2);
  q("g11_math", "Solve: 2ˣ = 16", ["x = 2", "x = 3", "x = 4", "x = 8"], 2);
  q("g11_math", "What is the value of (3 + 4i) + (2 - i) in complex numbers?", ["5 + 3i", "5 + 5i", "6 + 3i", "1 + 5i"], 0);
  q("g11_math", "What is the determinant of the matrix [[2,3],[1,4]]?", ["5", "8", "11", "4"], 0);
  q("g11_math", "What is the equation of a circle with centre (0,0) and radius 5?", ["x² + y² = 5", "x² + y² = 10", "x² + y² = 25", "x + y = 25"], 2);
  q("g11_math", "What is cos 60°?", ["0", "0.5", "1", "√3/2"], 1);
  q("g11_math", "What is the value of 4C2 (combinations)?", ["4", "6", "8", "12"], 1);
  q("g11_math", "Solve: 3x - 2 ≤ 10", ["x ≤ 4", "x ≤ 6", "x ≥ 4", "x ≥ 6"], 0);
  q("g11_math", "What is the standard deviation used to measure?", ["Central tendency", "Spread/dispersion of data", "Total of data", "Number of data points"], 1);
  q("g11_math", "If a die is rolled twice, what is the probability of getting two 6s?", ["1/6", "1/12", "1/36", "2/6"], 2);
  q("g11_math", "What is the gradient of a line perpendicular to y = 2x + 1?", ["2", "-2", "1/2", "-1/2"], 3);
  q("g11_math", "What is the value of 0! (0 factorial)?", ["0", "1", "Undefined", "-1"], 1);
  q("g11_math", "Simplify: (x² - 4)/(x - 2)", ["x - 2", "x + 2", "x²", "x - 4"], 1);
  q("g11_math", "What is the area under a velocity-time graph equal to?", ["Acceleration", "Distance", "Speed", "Time"], 1);
  q("g11_math", "What is the value of P(A) if event A is impossible?", ["1", "0.5", "0", "undefined"], 2);
  q("g11_math", "Solve for x: e^x = e^3", ["x = 1", "x = 2", "x = 3", "x = e"], 2);
  q("g11_math", "What is the next term in the GP: 2, 6, 18, 54, ___?", ["108", "144", "162", "180"], 2);
  q("g11_math", "What does the term \"asymptote\" describe?", ["A line a curve approaches but never touches", "The highest point of a curve", "The lowest point of a curve", "A point of intersection"], 0);
  q("g11_math", "What is the value of tan 0°?", ["0", "1", "undefined", "-1"], 0);
  q("g11_math", "What is the mean of a binomial distribution with n=10, p=0.5?", ["2.5", "5", "7.5", "10"], 1);

  // ---- Grade 12 ----
  addSubject("g12_eng", "English Language", "ENG", "high_school", "Grade 12");
  q("g12_eng", "What is the meaning of \"esoteric\"?", ["Widely known and understood", "Intended for a small, specialised group", "Simple and clear", "Ancient"], 1);
  q("g12_eng", "Identify the correctly formed sentence using inversion for emphasis.", ["Never I have seen such beauty.", "Never have I seen such beauty.", "I never have seen such beauty.", "Never seen I have such beauty."], 1);
  q("g12_eng", "What does \"magnanimous\" mean?", ["Petty and mean", "Generous and forgiving, especially toward a rival", "Cowardly", "Confused"], 1);
  q("g12_eng", "Identify the rhetorical device: \"We shall fight on the beaches, we shall fight on the landing grounds...\"", ["Anaphora", "Antithesis", "Onomatopoeia", "Litotes"], 0);
  q("g12_eng", "Choose the correct usage: \"Had I known, I ___ have come earlier.\"", ["would", "will", "shall", "can"], 0);
  q("g12_eng", "What is the meaning of \"perfunctory\"?", ["Done with care and enthusiasm", "Carried out with minimum effort, as a routine duty", "Thorough and detailed", "Delayed"], 1);
  q("g12_eng", "Identify the correctly spelt word.", ["Millennium", "Millenium", "Milennium", "Millenieum"], 0);
  q("g12_eng", "What is litotes?", ["A form of understatement using double negatives", "An exaggeration", "A direct comparison", "A rhyme scheme"], 0);
  q("g12_eng", "Choose the correct sentence.", ["Whom do you think will win?", "Who do you think will win?", "Whomever do you think will win?", "Who do you think whom will win?"], 1);
  q("g12_eng", "What is the meaning of \"ambivalent\"?", ["Having mixed or contradictory feelings", "Certain and decisive", "Angry", "Indifferent"], 0);
  q("g12_eng", "Identify the figure of speech: \"The classroom was a zoo.\"", ["Simile", "Metaphor", "Personification", "Euphemism"], 1);
  q("g12_eng", "What does \"prolific\" mean?", ["Producing much output or many works", "Rarely productive", "Slow", "Careful"], 0);
  q("g12_eng", "Choose the correct word: \"The two proposals are ___ similar.\"", ["each", "both", "either", "all"], 1);
  q("g12_eng", "What is a Petrarchan sonnet’s rhyme scheme for the octave?", ["ABAB CDCD", "ABBA ABBA", "AABB CCDD", "ABCA BCDB"], 1);
  q("g12_eng", "Identify the correct meaning of \"conundrum\".", ["An easy task", "A confusing and difficult problem or question", "A celebration", "A type of poem"], 1);
  q("g12_eng", "Identify the grammatically correct sentence.", ["Less people attended this year.", "Fewer people attended this year.", "Few people attended this year is.", "Lesser people attended this year."], 1);
  q("g12_eng", "What is the meaning of \"sycophant\"?", ["A rebel", "A person who flatters others to gain advantage", "A scholar", "A judge"], 1);
  q("g12_eng", "Identify the literary term: repetition of initial consonant sounds.", ["Assonance", "Alliteration", "Consonance", "Rhyme"], 1);
  q("g12_eng", "Choose the correct word: \"The report was ___ with errors.\"", ["replete", "complete", "depleted", "deplete"], 0);
  q("g12_eng", "What does \"tacit\" mean?", ["Spoken loudly", "Understood without being stated", "Aggressive", "Written formally"], 1);
  q("g12_eng", "Identify the correctly formed comparative: \"This is the ___ of the two options.\"", ["best", "better", "good", "well"], 1);
  q("g12_eng", "What is a bildungsroman?", ["A novel dealing with a character’s formative years/moral growth", "A type of poem", "A comedic play", "A short story with a twist"], 0);
  q("g12_eng", "Choose the correctly spelt word.", ["Questionaire", "Questionnaire", "Questionnair", "Questionair"], 1);
  q("g12_eng", "What does \"laconic\" describe?", ["Someone who talks excessively", "Someone who uses very few words", "Someone who is confused", "Someone who is dishonest"], 1);
  q("g12_eng", "Identify the mood expressed: \"Would that I had listened to her advice.\"", ["Indicative", "Subjunctive", "Imperative", "Interrogative"], 1);
  q("g12_eng", "What is the meaning of \"dichotomy\"?", ["A division into two contrasting parts", "A single unified idea", "A rhyme scheme", "A type of essay"], 0);
  q("g12_eng", "Choose the correct usage: \"Not only did she win, ___ she also broke the record.\"", ["and", "but", "so", "or"], 1);

  addSubject("g12_math", "Mathematics", "MTH", "high_school", "Grade 12");
  q("g12_math", "What is the derivative of sin x?", ["cos x", "-cos x", "-sin x", "tan x"], 0);
  q("g12_math", "What is ∫(3x²)dx?", ["x³ + C", "3x³ + C", "6x + C", "x³/3 + C"], 0);
  q("g12_math", "Solve for x: e^(2x) = e^6", ["x = 2", "x = 3", "x = 6", "x = 12"], 1);
  q("g12_math", "What is the limit of (sin x)/x as x approaches 0?", ["0", "1", "undefined", "infinity"], 1);
  q("g12_math", "What is the second derivative of x⁴?", ["4x³", "12x²", "16x²", "12x³"], 1);
  q("g12_math", "Find the inverse of f(x) = 2x + 3.", ["(x-3)/2", "(x+3)/2", "2x - 3", "(x-2)/3"], 0);
  q("g12_math", "What is the sum of the roots of x² - 5x + 6 = 0 (using sum = -b/a)?", ["-5", "5", "6", "-6"], 1);
  q("g12_math", "What is the product of the roots of x² - 5x + 6 = 0?", ["5", "-5", "6", "-6"], 2);
  q("g12_math", "What is the modulus of the complex number 3 + 4i?", ["3", "4", "5", "7"], 2);
  q("g12_math", "What is the derivative of ln x?", ["x", "1/x", "ln x", "e^x"], 1);
  q("g12_math", "Evaluate: lim(x→2) (x² - 4)/(x - 2)", ["0", "2", "4", "undefined"], 2);
  q("g12_math", "What is the value of 5P3 (permutations)?", ["15", "60", "10", "20"], 1);
  q("g12_math", "What is the equation of a parabola with vertex at the origin opening upward, given a=1?", ["y = x", "y = x²", "x = y²", "y = 2x"], 1);
  q("g12_math", "What matrix operation is used to solve simultaneous equations directly?", ["Addition", "Transposition", "Inverse matrix multiplication", "Scalar multiplication"], 2);
  q("g12_math", "What is the derivative of e^(3x)?", ["e^(3x)", "3e^(3x)", "3xe^(3x-1)", "e^3"], 1);
  q("g12_math", "A binomial distribution has n = 20, p = 0.3. What is the mean?", ["3", "6", "9", "14"], 1);
  q("g12_math", "What is the value of i² (where i = √-1)?", ["1", "-1", "i", "0"], 1);
  q("g12_math", "What condition makes a quadratic equation have equal roots?", ["b² - 4ac > 0", "b² - 4ac = 0", "b² - 4ac < 0", "b² - 4ac = 1"], 1);
  q("g12_math", "What is the area under the curve y = x from x=0 to x=4?", ["4", "8", "16", "2"], 1);
  q("g12_math", "What is the formula for the nth term of a geometric progression?", ["a + (n-1)d", "ar^(n-1)", "a×n", "a/(n-1)"], 1);
  q("g12_math", "What does the correlation coefficient r = 1 indicate?", ["No correlation", "Perfect negative correlation", "Perfect positive correlation", "Weak correlation"], 2);
  q("g12_math", "What is the stationary point of y = x² - 4x + 3?", ["(1,0)", "(2,-1)", "(2,1)", "(-2,-1)"], 1);
  q("g12_math", "What is the value of cos⁻¹(1)?", ["0°", "90°", "180°", "45°"], 0);
  q("g12_math", "Simplify: log a + log b", ["log(a+b)", "log(ab)", "log(a/b)", "log a × log b"], 1);
  q("g12_math", "What is the rate of change represented by a derivative?", ["Average rate of change", "Instantaneous rate of change", "Total change", "Cumulative sum"], 1);
  q("g12_math", "A committee of 3 is chosen from 8 people. How many ways can this be done?", ["24", "56", "336", "168"], 1);
  q("g12_math", "What is the value of ∑(1 to 5) n (sum of first 5 natural numbers)?", ["10", "15", "20", "25"], 1);


  // ---------------- COLLEGE ----------------
  addSubject("col_eng", "Use of English", "ENG", "college", null);
  q("col_eng", "Choose the word nearest in meaning to \"abate\".", ["Increase", "Reduce", "Ignore", "Begin"], 1);
  q("col_eng", "Identify the correctly spelt word.", ["Maintainance", "Maintenance", "Maintainence", "Maintanence"], 1);
  q("col_eng", "Choose the correct word: \"The company’s profits ___ significantly last year.\"", ["rose", "raised", "rise", "rises"], 0);
  q("col_eng", "What is the meaning of \"explicit\"?", ["Vague", "Clearly stated, leaving no room for doubt", "Hidden", "Brief"], 1);
  q("col_eng", "Choose the correct sentence.", ["Everyone must bring their own lunch.", "Everyone must bring his or her own lunch.", "Everyone must bring they own lunch.", "Everyone must bring its own lunch."], 1);
  q("col_eng", "What is a synonym for \"meticulous\"?", ["Careless", "Thorough", "Quick", "Lazy"], 1);
  q("col_eng", "Choose the correctly punctuated sentence.", ["I have three goals; save money, travel, and read more.", "I have three goals: save money, travel, and read more.", "I have three goals, save money, travel, and read more.", "I have three goals save money, travel, and read more."], 1);
  q("col_eng", "What does \"consensus\" mean?", ["Disagreement", "General agreement", "A vote", "A committee"], 1);
  q("col_eng", "Identify the correct word: \"The lecture was ___ boring that half the class fell asleep.\"", ["so", "such", "too", "very"], 0);
  q("col_eng", "What is the antonym of \"reluctant\"?", ["Hesitant", "Willing", "Unsure", "Slow"], 1);
  q("col_eng", "Choose the correct comprehension skill: identifying the writer’s attitude is called?", ["Skimming", "Tone analysis", "Scanning", "Paraphrasing"], 1);
  q("col_eng", "What does \"concise\" mean?", ["Giving information in a short, clear way", "Long and detailed", "Confusing", "Repetitive"], 0);
  q("col_eng", "Choose the correct word: \"He is ___ to succeed given his preparation.\"", ["likely", "likelihood", "like", "liking"], 0);
  q("col_eng", "What is the meaning of \"corroborate\"?", ["To contradict", "To confirm or support with evidence", "To ignore", "To question"], 1);
  q("col_eng", "Identify the correctly formed sentence.", ["Not only he is smart but also hardworking.", "Not only is he smart but also hardworking.", "Not only he smart but also hardworking.", "He not only is smart but hardworking."], 1);
  q("col_eng", "What is skimming in reading comprehension?", ["Reading quickly for the main idea", "Reading slowly for detail", "Reading aloud", "Reading backward"], 0);
  q("col_eng", "Choose the correct usage of \"fewer\" vs \"less\": \"There are ___ students this year.\"", ["less", "fewer", "lesser", "few"], 1);
  q("col_eng", "What does \"redundant\" mean in writing?", ["Necessary and clear", "Unnecessarily repetitive", "Brief", "Formal"], 1);
  q("col_eng", "Identify the topic sentence’s role in a paragraph.", ["States the main idea of the paragraph", "Gives an example", "Provides a conclusion", "Lists references"], 0);
  q("col_eng", "Choose the correct word: \"The data ___ inconclusive.\"", ["is", "are", "was", "has"], 1);
  q("col_eng", "What is the meaning of \"coherent\" in writing?", ["Logical and well-organised", "Confusing", "Overly long", "Informal"], 0);
  q("col_eng", "Identify the correct antonym of \"verbose\".", ["Wordy", "Concise", "Detailed", "Lengthy"], 1);
  q("col_eng", "What technique involves looking for specific information quickly in a text?", ["Skimming", "Scanning", "Summarising", "Inferring"], 1);
  q("col_eng", "Identify the grammatically correct sentence.", ["She along with her friends were late.", "She along with her friends was late.", "She along with her friends is late.", "She along with her friends being late."], 1);
  q("col_eng", "What does \"infer\" mean in comprehension?", ["To state directly", "To conclude from evidence and reasoning", "To repeat", "To summarise word-for-word"], 1);
  q("col_eng", "Identify the correct word: \"The manager gave clear and ___ instructions.\"", ["concise", "concize", "consise", "consize"], 0);
  q("col_eng", "What is a thesis statement?", ["The main argument or claim of an essay", "A summary of a text", "A list of references", "A footnote"], 0);

  addSubject("col_gk", "General Knowledge", "GK", "college", null);
  q("col_gk", "In what year did Nigeria gain independence?", ["1957", "1960", "1963", "1970"], 1);
  q("col_gk", "What is the largest planet in our solar system?", ["Earth", "Saturn", "Jupiter", "Neptune"], 2);
  q("col_gk", "Who wrote \"Things Fall Apart\"?", ["Wole Soyinka", "Chinua Achebe", "Chimamanda Adichie", "Cyprian Ekwensi"], 1);
  q("col_gk", "What is the chemical symbol for gold?", ["Go", "Gd", "Au", "Ag"], 2);
  q("col_gk", "Which African river is the longest?", ["Niger", "Congo", "Nile", "Zambezi"], 2);
  q("col_gk", "What does \"UTME\" stand for?", ["Unified Tertiary Matriculation Examination", "United Test for Matriculating Entrants", "Universal Tertiary Merit Exam", "Unified Test of Manpower Education"], 0);
  q("col_gk", "What is the currency of Nigeria?", ["Cedi", "Naira", "Franc", "Rand"], 1);
  q("col_gk", "Which is the smallest country in the world by land area?", ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], 1);
  q("col_gk", "What is the capital of Nigeria?", ["Lagos", "Kano", "Abuja", "Port Harcourt"], 2);
  q("col_gk", "Who was the first President of Nigeria?", ["Nnamdi Azikiwe", "Tafawa Balewa", "Yakubu Gowon", "Olusegun Obasanjo"], 0);
  q("col_gk", "What is the largest continent by area?", ["Africa", "Asia", "North America", "Europe"], 1);
  q("col_gk", "What gas do plants primarily absorb for photosynthesis?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], 2);
  q("col_gk", "What is the tallest mountain in Africa?", ["Mount Kenya", "Mount Kilimanjaro", "Mount Cameroon", "Table Mountain"], 1);
  q("col_gk", "Which organisation is Nigeria a founding member of, established in 1963?", ["UN", "OAU (now AU)", "ECOWAS", "NATO"], 1);
  q("col_gk", "What is the boiling point of water at sea level in Celsius?", ["90°C", "100°C", "110°C", "120°C"], 1);
  q("col_gk", "Who is regarded as the father of modern computing?", ["Albert Einstein", "Alan Turing", "Isaac Newton", "Nikola Tesla"], 1);
  q("col_gk", "What year did World War II end?", ["1943", "1945", "1947", "1950"], 1);
  q("col_gk", "What is the official language of Nigeria?", ["French", "English", "Hausa", "Portuguese"], 1);
  q("col_gk", "Which planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Mercury"], 1);
  q("col_gk", "What is the SI unit of electric current?", ["Volt", "Watt", "Ampere", "Ohm"], 2);
  q("col_gk", "Which body organ is primarily responsible for pumping blood?", ["Lungs", "Liver", "Heart", "Kidney"], 2);
  q("col_gk", "What is the largest ocean on Earth?", ["Atlantic", "Indian", "Arctic", "Pacific"], 3);
  q("col_gk", "Who developed the theory of relativity?", ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"], 1);
  q("col_gk", "What is the smallest unit of life?", ["Tissue", "Organ", "Cell", "Organelle"], 2);
  q("col_gk", "Which Nigerian city is known as the \"Centre of Excellence\"?", ["Abuja", "Lagos", "Kano", "Ibadan"], 1);
  q("col_gk", "What is the primary function of the United Nations?", ["To control global trade", "To maintain international peace and security", "To issue currency", "To govern individual nations directly"], 1);
  q("col_gk", "How many continents are there?", ["5", "6", "7", "8"], 2);


  // ---------------- PROFESSIONAL BODIES ----------------
  addSubject("prof_ican", "ICAN Foundation — Financial Accounting", "ICAN", "professional", null);
  q("prof_ican", "What is the accounting equation?", ["Assets = Liabilities - Equity", "Assets = Liabilities + Equity", "Assets + Liabilities = Equity", "Equity = Assets + Liabilities"], 1);
  q("prof_ican", "Which financial statement shows a company’s profit over a period?", ["Balance Sheet", "Income Statement", "Cash Flow Statement", "Statement of Equity"], 1);
  q("prof_ican", "A debit entry in a personal account represents what?", ["A liability", "An amount owed to the person", "An amount the person owes", "Nothing"], 2);
  q("prof_ican", "What does \"depreciation\" represent?", ["Increase in asset value", "Allocation of an asset’s cost over its useful life", "A type of revenue", "A liability"], 1);
  q("prof_ican", "Which of these is a current asset?", ["Building", "Inventory", "Goodwill", "Long-term investment"], 1);
  q("prof_ican", "What is the purpose of a trial balance?", ["To calculate tax", "To check that debits equal credits", "To record sales", "To pay employees"], 1);
  q("prof_ican", "Which principle states expenses should be recorded when incurred, not when paid?", ["Cash basis", "Accrual basis", "Conservatism", "Materiality"], 1);
  q("prof_ican", "What is \"double-entry bookkeeping\"?", ["Recording each transaction once", "Recording each transaction in two accounts", "Recording only cash transactions", "A tax filing method"], 1);
  q("prof_ican", "Which body regulates accountancy practice in Nigeria?", ["ICAN", "NBA", "CIBN", "COREN"], 0);
  q("prof_ican", "What does \"liquidity\" measure?", ["Profitability", "Ability to meet short-term obligations", "Long-term growth", "Market share"], 1);
  q("prof_ican", "What is a \"credit note\" used for?", ["Recording a purchase", "Reducing the amount a customer owes, e.g. for returns", "Increasing sales", "Recording payroll"], 1);
  q("prof_ican", "What is \"working capital\"?", ["Total assets minus total liabilities", "Current assets minus current liabilities", "Fixed assets only", "Total revenue"], 1);
  q("prof_ican", "What does FIFO stand for in inventory valuation?", ["First In, First Out", "Fixed Inventory, Flexible Output", "First Input, Final Output", "Full Inventory For Operations"], 0);
  q("prof_ican", "Which of these is an intangible asset?", ["Machinery", "Cash", "Goodwill", "Inventory"], 2);
  q("prof_ican", "What is a \"bank reconciliation statement\" used for?", ["To calculate profit", "To match the cash book balance with the bank statement balance", "To record fixed assets", "To calculate depreciation"], 1);
  q("prof_ican", "What is \"gross profit\"?", ["Sales minus cost of sales", "Sales minus all expenses", "Total revenue", "Net income"], 0);
  q("prof_ican", "What financial statement shows assets, liabilities and equity at a point in time?", ["Income statement", "Cash flow statement", "Balance sheet", "Trial balance"], 2);
  q("prof_ican", "What does \"amortisation\" apply to?", ["Tangible assets only", "Intangible assets", "Cash", "Liabilities only"], 1);
  q("prof_ican", "What is a \"contra entry\"?", ["A transaction affecting both cash and bank accounts", "An error in posting", "A type of asset", "A tax deduction"], 0);
  q("prof_ican", "What does the matching concept in accounting require?", ["Revenue and related expenses recorded in the same period", "All transactions recorded in cash", "Assets matched to liabilities", "Equal debit and credit accounts only"], 0);
  q("prof_ican", "What is a \"provision\" in accounting?", ["A known exact liability", "A liability of uncertain timing or amount", "An asset", "A type of revenue"], 1);
  q("prof_ican", "What does ROI stand for?", ["Rate of Interest", "Return on Investment", "Ratio of Income", "Revenue of Institution"], 1);
  q("prof_ican", "What is the going concern concept?", ["Assumes a business will continue operating in the foreseeable future", "Assumes a business will close soon", "Relates only to cash transactions", "A tax rule"], 0);
  q("prof_ican", "What is \"net realisable value\" used for?", ["Valuing inventory at the lower of cost and NRV", "Calculating tax", "Valuing fixed assets only", "Recording payroll"], 0);
  q("prof_ican", "Which of these best describes a \"suspense account\"?", ["A temporary account used when a trial balance doesn’t balance", "A permanent revenue account", "An account for fixed assets", "A tax account"], 0);
  q("prof_ican", "What is \"capital expenditure\"?", ["Spending on day-to-day operations", "Spending to acquire or improve long-term assets", "Spending on wages only", "A type of revenue"], 1);
  q("prof_ican", "What does \"prudence concept\" advise?", ["Overstate profits", "Not overstate assets/income or understate liabilities/expenses", "Ignore uncertainties", "Record only cash transactions"], 1);

  addSubject("prof_nba", "NBA (Law School) — Introduction to Law", "NBA", "professional", null);
  q("prof_nba", "What is the primary source of Nigerian law?", ["Case law only", "The Constitution", "Customary law only", "Religious law"], 1);
  q("prof_nba", "What does \"stare decisis\" mean?", ["Let the decision stand (binding precedent)", "Innocent until proven guilty", "Equity before law", "Right to remain silent"], 0);
  q("prof_nba", "What is a \"tort\"?", ["A type of contract", "A civil wrong causing harm", "A criminal offence only", "A type of legislation"], 1);
  q("prof_nba", "Who has original jurisdiction over election petitions for governorship in Nigeria?", ["Supreme Court", "Court of Appeal", "Federal High Court", "Election Petition Tribunal"], 3);
  q("prof_nba", "What is the doctrine of \"presumption of innocence\"?", ["Accused must prove innocence", "Accused is presumed innocent until proven guilty", "Only applies to civil cases", "Applies only to minors"], 1);
  q("prof_nba", "What does \"ultra vires\" mean?", ["Within power", "Beyond one’s legal power", "By force of law", "Under review"], 1);
  q("prof_nba", "Which court is the highest in Nigeria?", ["Court of Appeal", "Federal High Court", "Supreme Court", "High Court"], 2);
  q("prof_nba", "What is \"consideration\" in contract law?", ["A moral obligation", "Something of value exchanged between parties", "A type of court", "A witness statement"], 1);
  q("prof_nba", "What is the age of majority in Nigeria for most legal purposes?", ["16", "18", "21", "25"], 1);
  q("prof_nba", "What does \"habeas corpus\" protect?", ["Right to property", "Right against unlawful detention", "Right to vote", "Right to free speech"], 1);
  q("prof_nba", "What is \"mens rea\"?", ["The guilty act", "The guilty mind/intention", "A type of defence", "A civil remedy"], 1);
  q("prof_nba", "What is \"actus reus\"?", ["The guilty mind", "The guilty act", "A type of contract", "A legal defence"], 1);
  q("prof_nba", "What does \"bona fide\" mean?", ["In bad faith", "In good faith, genuine", "Under duress", "Void"], 1);
  q("prof_nba", "What is a \"plaintiff\"?", ["The person defending a case", "The person bringing a civil case to court", "The judge", "A witness"], 1);
  q("prof_nba", "What is the meaning of \"in loco parentis\"?", ["In place of a parent", "Under the law", "By order of the court", "In the presence of a lawyer"], 0);
  q("prof_nba", "What is a \"precedent\" in law?", ["A future ruling", "A previous case decision used as authority for later cases", "A type of statute", "A legal fee"], 1);
  q("prof_nba", "What arm of government interprets the law in Nigeria?", ["Executive", "Legislature", "Judiciary", "Civil Service"], 2);
  q("prof_nba", "What does \"res judicata\" mean?", ["A matter already judged, which cannot be re-litigated", "A pending case", "An appeal", "A settlement"], 0);
  q("prof_nba", "What is a \"writ of summons\"?", ["A document that begins a civil action", "A criminal charge sheet", "A search warrant", "A judgment"], 0);
  q("prof_nba", "What does the term \"locus standi\" refer to?", ["The right or capacity to bring a case before a court", "The location of the court", "A legal defence", "A type of remedy"], 0);
  q("prof_nba", "What is \"customary law\" in Nigeria?", ["Law made by the National Assembly", "Indigenous law based on the customs of a community", "International treaties", "Case law from foreign courts"], 1);
  q("prof_nba", "What does \"burden of proof\" mean in a criminal trial?", ["The defendant must prove innocence", "The prosecution must prove guilt beyond reasonable doubt", "The judge decides without evidence", "Only applies in civil cases"], 1);
  q("prof_nba", "What is \"damages\" in civil law?", ["A criminal penalty", "Monetary compensation awarded for loss or injury", "A type of contract", "A court fee"], 1);
  q("prof_nba", "What does \"void ab initio\" mean?", ["Valid from the start", "Invalid from the very beginning", "Valid only in future", "Pending review"], 1);
  q("prof_nba", "What is the standard of proof in civil cases in Nigeria?", ["Beyond reasonable doubt", "Balance of probabilities", "Absolute certainty", "No standard required"], 1);
  q("prof_nba", "What is \"jurisdiction\"?", ["The power of a court to hear and decide a case", "A type of legal fee", "A witness statement", "A form of punishment"], 0);
  q("prof_nba", "What does the fundamental right to fair hearing guarantee?", ["A private trial only", "The right to be heard by an impartial tribunal", "Automatic acquittal", "Free legal representation always"], 1);

  addSubject("prof_rmafc", "RMAFC — Public Finance Basics", "RMAFC", "professional", null);
  q("prof_rmafc", "What does RMAFC stand for?", ["Revenue Mobilisation Allocation and Fiscal Commission", "Regional Monetary and Financial Council", "Revenue Management and Federal Commission", "Revenue Mobilisation Agency for Finance Control"], 0);
  q("prof_rmafc", "What is \"fiscal federalism\"?", ["A single national tax system", "Distribution of financial responsibilities between government tiers", "A type of currency", "A banking regulation"], 1);
  q("prof_rmafc", "What is the main source of revenue for the Nigerian federal government?", ["Import duties", "Oil revenue", "Personal income tax", "Company registration fees"], 1);
  q("prof_rmafc", "What is a \"derivation principle\" in revenue allocation?", ["Equal sharing regardless of origin", "Allocating revenue based on where it was generated", "A fixed federal quota", "A tax exemption rule"], 1);
  q("prof_rmafc", "Which document outlines Nigeria’s annual government spending plan?", ["The Constitution", "The Budget", "The Gazette", "The Treaty"], 1);
  q("prof_rmafc", "What is \"vertical revenue allocation\"?", ["Sharing revenue among states only", "Sharing revenue between federal, state, and local governments", "Sharing revenue between companies", "A type of tax"], 1);
  q("prof_rmafc", "What body determines salaries and allowances of political office holders in Nigeria?", ["RMAFC", "INEC", "NNPC", "CBN"], 0);
  q("prof_rmafc", "What is a \"fiscal deficit\"?", ["When revenue exceeds expenditure", "When expenditure exceeds revenue", "A balanced budget", "A type of tax refund"], 1);
  q("prof_rmafc", "What is VAT?", ["Value Added Tax", "Variable Allocation Tariff", "Vertical Assessment Tax", "Value Assurance Trust"], 0);
  q("prof_rmafc", "What percentage tier receives the largest share in Nigeria’s statutory revenue allocation formula?", ["Local government", "State government", "Federal government", "Federal Capital Territory"], 2);
  q("prof_rmafc", "What is \"horizontal revenue allocation\"?", ["Sharing revenue among states/local governments at the same tier", "Sharing revenue between federal and states", "A tax on imports", "A type of loan"], 0);
  q("prof_rmafc", "What does \"public debt\" refer to?", ["Money owed by individuals", "Money owed by government to creditors", "Company debt only", "Bank reserves"], 1);
  q("prof_rmafc", "What is the role of the Federation Account?", ["A private company account", "A pool where federally collected revenue is shared among tiers of government", "A personal savings scheme", "A tax refund system"], 1);
  q("prof_rmafc", "What is \"internally generated revenue\" (IGR)?", ["Revenue generated by a state/LG from its own sources", "Revenue from the federal government only", "Foreign aid", "Loans from banks"], 0);
  q("prof_rmafc", "What does \"fiscal policy\" refer to?", ["Government use of spending and taxation to influence the economy", "Central bank control of money supply", "Trade agreements only", "Company accounting rules"], 0);
  q("prof_rmafc", "What is a \"subsidy\"?", ["A tax increase", "Financial assistance given by government to reduce cost of a good/service", "A type of loan", "A penalty"], 1);
  q("prof_rmafc", "What does \"budget deficit financing\" involve?", ["Reducing spending only", "Borrowing or other means to cover a budget shortfall", "Increasing taxes only", "Selling government assets exclusively"], 1);
  q("prof_rmafc", "What is the purpose of a Medium-Term Expenditure Framework (MTEF)?", ["A one-year emergency plan", "A 3-year framework guiding budget planning and fiscal projections", "A tax collection method", "A type of audit"], 1);
  q("prof_rmafc", "What does \"excess crude account\" hold?", ["Savings from oil revenue above the budgeted benchmark price", "Tax revenue only", "Loans from the IMF", "Company profits"], 0);
  q("prof_rmafc", "What is \"revenue mobilisation\"?", ["Spending government funds", "The process of generating and collecting government revenue", "Reducing taxes", "Foreign investment only"], 1);
  q("prof_rmafc", "What does PAYE stand for in personal taxation?", ["Pay As You Earn", "Public Accounts Yearly Estimate", "Payment After Yearly Evaluation", "Personal Annual Yield Estimate"], 0);
  q("prof_rmafc", "What is the role of the Auditor-General in public finance?", ["To set tax rates", "To audit and report on public accounts", "To approve the budget", "To print currency"], 1);
  q("prof_rmafc", "What is \"capital budget\" used for?", ["Recurrent expenditure like salaries", "Long-term investment in infrastructure and development projects", "Debt servicing only", "Foreign aid distribution"], 1);
  q("prof_rmafc", "What does \"recurrent expenditure\" cover?", ["Infrastructure projects", "Day-to-day running costs like salaries and overheads", "Capital investments only", "Loan repayments only"], 1);
  q("prof_rmafc", "Which arm of government approves the national budget in Nigeria?", ["Executive", "National Assembly (Legislature)", "Judiciary", "Civil Service"], 1);
  q("prof_rmafc", "What is a \"tax haven\"?", ["A country with high tax rates", "A jurisdiction offering low or no taxes to attract businesses", "A government tax office", "A type of subsidy"], 1);
  q("prof_rmafc", "What does \"inflation\" do to the value of money over time?", ["Increases its purchasing power", "Decreases its purchasing power", "Has no effect", "Doubles it instantly"], 1);

  addSubject("prof_cibn", "CIBN — Banking Fundamentals", "CIBN", "professional", null);
  q("prof_cibn", "What does CIBN stand for?", ["Chartered Institute of Bankers of Nigeria", "Central Institute of Banking Nigeria", "Commercial Institute of Bankers Nigeria", "Council of Independent Bankers Nigeria"], 0);
  q("prof_cibn", "What is the primary role of the Central Bank of Nigeria?", ["Issuing loans to individuals", "Regulating monetary policy and currency issuance", "Selling insurance", "Running commercial banks"], 1);
  q("prof_cibn", "What is \"collateral\" in banking?", ["A type of loan", "An asset pledged to secure a loan", "A bank fee", "An interest rate"], 1);
  q("prof_cibn", "What does \"KYC\" stand for in banking compliance?", ["Keep Your Cash", "Know Your Customer", "Key Yield Calculation", "Know Your Currency"], 1);
  q("prof_cibn", "What is a \"non-performing loan\"?", ["A loan that has been fully repaid", "A loan in default or close to default", "A new loan application", "A loan with no interest"], 1);
  q("prof_cibn", "What is the purpose of a \"cheque\"?", ["A savings instrument", "A written order to pay a specific amount", "A type of loan", "An investment bond"], 1);
  q("prof_cibn", "What does \"liquidity ratio\" measure in a bank?", ["Profitability", "Ability to meet short-term obligations", "Staff efficiency", "Market share"], 1);
  q("prof_cibn", "What is \"inflation\"?", ["A fall in general price levels", "A rise in general price levels over time", "A fixed exchange rate", "A type of bank fee"], 1);
  q("prof_cibn", "What is the full meaning of \"ATM\"?", ["Automated Teller Machine", "Automatic Transfer Module", "Account Transaction Manager", "Authorized Teller Method"], 0);
  q("prof_cibn", "What is a \"bank run\"?", ["A marketing campaign", "Many customers withdrawing funds at once due to fear of insolvency", "A daily banking routine", "A type of loan repayment"], 1);
  q("prof_cibn", "What is the \"monetary policy rate\" (MPR)?", ["The interest rate banks charge each other for savings", "The benchmark interest rate set by the central bank", "A fixed exchange rate", "A type of tax"], 1);
  q("prof_cibn", "What is \"microfinance banking\" aimed at?", ["Serving large corporations only", "Providing financial services to low-income individuals and small businesses", "International trade only", "Government funding only"], 1);
  q("prof_cibn", "What does \"overdraft\" mean?", ["A savings account", "Withdrawing more money than is in an account, within an agreed limit", "A fixed deposit", "A type of cheque"], 1);
  q("prof_cibn", "What is the purpose of the Nigeria Deposit Insurance Corporation (NDIC)?", ["To issue currency", "To insure bank deposits and protect depositors", "To regulate stock exchanges", "To collect taxes"], 1);
  q("prof_cibn", "What is \"electronic funds transfer\" (EFT)?", ["Physical cash delivery", "Digital movement of money between accounts", "A type of cheque only", "A loan product"], 1);
  q("prof_cibn", "What does \"credit risk\" refer to?", ["The risk a bank’s building will be damaged", "The risk a borrower will fail to repay a loan", "The risk of currency devaluation only", "Staff turnover risk"], 1);
  q("prof_cibn", "What is a \"fixed deposit account\"?", ["An account with unlimited withdrawals", "A savings account where funds are locked for a set period at a fixed interest rate", "A current account", "A loan account"], 1);
  q("prof_cibn", "What is the primary function of commercial banks?", ["Setting national fiscal policy", "Accepting deposits and providing loans to individuals and businesses", "Printing currency", "Regulating the stock exchange"], 1);
  q("prof_cibn", "What does \"capital adequacy ratio\" measure?", ["A bank’s ability to absorb losses relative to its risk-weighted assets", "Customer satisfaction", "Staff productivity", "Branch network size"], 0);
  q("prof_cibn", "What is \"mobile banking\"?", ["Banking services accessed via mobile devices", "A bank branch on wheels", "A type of savings bond", "A currency exchange service"], 0);
  q("prof_cibn", "What is the role of a \"loan officer\"?", ["To manage IT systems", "To evaluate and process loan applications", "To audit financial statements", "To set interest rates nationally"], 1);
  q("prof_cibn", "What does \"exchange rate\" refer to?", ["The rate at which one currency is exchanged for another", "The interest rate on loans", "The tax rate on income", "The inflation rate"], 0);
  q("prof_cibn", "What is \"financial inclusion\"?", ["Restricting banking to the wealthy", "Ensuring individuals and businesses have access to useful financial services", "A tax policy", "A type of insurance"], 1);
  q("prof_cibn", "What does \"prime lending rate\" mean?", ["The lowest rate offered to a bank’s most creditworthy customers", "The highest possible interest rate", "A fixed government rate", "A savings account rate"], 0);
  q("prof_cibn", "What is the purpose of \"anti-money laundering\" (AML) regulations?", ["To promote money laundering", "To detect and prevent the disguising of illegally obtained funds", "To increase bank profits", "To reduce customer numbers"], 1);
  q("prof_cibn", "What is a \"letter of credit\" used for in trade?", ["A personal loan document", "A bank guarantee ensuring payment to a seller in international trade", "A tax receipt", "A savings certificate"], 1);
  q("prof_cibn", "What does \"BVN\" stand for in Nigerian banking?", ["Bank Verification Number", "Bank Value Note", "Business Venture Number", "Basic Vault Number"], 0);

  addSubject("prof_coren", "COREN — Engineering Fundamentals", "COREN", "professional", null);
  q("prof_coren", "What does COREN stand for?", ["Council for the Regulation of Engineering in Nigeria", "Corporation of Registered Engineers of Nigeria", "Central Office for Regulation of Engineering Nigeria", "Council of Registered Engineering Nations"], 0);
  q("prof_coren", "What is the SI unit of force?", ["Watt", "Newton", "Joule", "Pascal"], 1);
  q("prof_coren", "What does \"factor of safety\" refer to in engineering design?", ["The exact load a structure will fail at", "A ratio ensuring a structure can withstand more than expected load", "A type of insurance", "The cost of materials"], 1);
  q("prof_coren", "Which law states that force equals mass times acceleration?", ["Newton’s First Law", "Newton’s Second Law", "Newton’s Third Law", "Law of Conservation of Energy"], 1);
  q("prof_coren", "What is the unit of electrical resistance?", ["Volt", "Ampere", "Ohm", "Watt"], 2);
  q("prof_coren", "What does \"COREN registration\" grant an engineer in Nigeria?", ["A university degree", "Legal right to practice as a professional engineer", "A driving license", "A business permit"], 1);
  q("prof_coren", "What is \"tensile strength\"?", ["Resistance to compression", "Maximum stress a material can withstand while being stretched", "The weight of a material", "The color of a material"], 1);
  q("prof_coren", "What is the primary purpose of a structural beam?", ["To decorate a building", "To resist bending loads", "To provide electrical wiring", "To store water"], 1);
  q("prof_coren", "What does \"civil engineering\" primarily deal with?", ["Software design", "Design and construction of infrastructure", "Medical devices", "Financial systems"], 1);
  q("prof_coren", "What is Ohm’s Law?", ["V = IR", "F = ma", "E = mc²", "P = VI only"], 0);
  q("prof_coren", "What is the unit of power in the SI system?", ["Joule", "Newton", "Watt", "Pascal"], 2);
  q("prof_coren", "What does \"stress\" mean in engineering mechanics?", ["Force per unit area", "Change in length", "A type of material", "Total weight"], 0);
  q("prof_coren", "What is \"strain\" in engineering mechanics?", ["Force applied to a material", "The deformation of a material relative to its original length", "The weight of a structure", "A unit of pressure"], 1);
  q("prof_coren", "What is the purpose of a \"factor of safety\" greater than 1?", ["To reduce construction cost", "To provide a margin against uncertainty and overload", "To make the design heavier", "To speed up construction"], 1);
  q("prof_coren", "What does \"mechanical engineering\" primarily involve?", ["Design, analysis, and manufacture of mechanical systems", "Legal contract drafting", "Financial auditing", "Medical diagnosis"], 0);
  q("prof_coren", "What is Young’s Modulus a measure of?", ["A material’s stiffness/elasticity", "A material’s weight", "A material’s color", "A material’s cost"], 0);
  q("prof_coren", "What does \"electrical engineering\" primarily deal with?", ["Study and application of electricity, electronics, and electromagnetism", "Construction of roads", "Water treatment only", "Financial systems"], 0);
  q("prof_coren", "What is the function of a \"capacitor\" in a circuit?", ["To generate electricity", "To store electrical energy", "To measure voltage", "To convert AC to mechanical energy"], 1);
  q("prof_coren", "What is the primary purpose of continuing professional development (CPD) for COREN-registered engineers?", ["To increase registration fees", "To keep engineers updated with current knowledge and practice", "To reduce the number of engineers", "To replace university education"], 1);
  q("prof_coren", "What does \"load-bearing wall\" mean?", ["A decorative wall", "A wall that supports the structural weight above it", "A temporary partition", "A wall with windows only"], 1);
  q("prof_coren", "What is the unit of frequency?", ["Hertz", "Watt", "Ohm", "Newton"], 0);
  q("prof_coren", "What is \"thermodynamics\" the study of?", ["Motion of objects", "Heat, energy, and their conversion to work", "Electrical circuits", "Structural loads"], 1);
  q("prof_coren", "What does \"torque\" measure?", ["Linear force", "Rotational force", "Electrical resistance", "Heat energy"], 1);
  q("prof_coren", "What is a \"prototype\" in engineering design?", ["The final mass-produced product", "An early sample or model built to test a concept", "A marketing document", "A financial report"], 1);
  q("prof_coren", "What is the purpose of quality control in engineering projects?", ["To increase project cost", "To ensure work meets required standards and specifications", "To delay project completion", "To reduce safety"], 1);
  q("prof_coren", "What does \"fatigue failure\" in materials refer to?", ["Failure due to a single large load", "Failure due to repeated cyclic loading over time", "Failure due to corrosion only", "Failure due to temperature alone"], 1);
  q("prof_coren", "What is the role of an engineer’s professional code of ethics?", ["To maximise personal profit", "To guide responsible, safe, and honest professional conduct", "To restrict competition", "To avoid registration fees"], 1);

  return { subjects, questionsBySubjectKey };
}

if (typeof window !== 'undefined') {
  window.buildDemoContent = buildDemoContent;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { buildDemoContent };
}
